// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.20.3
// source: foo.proto

package test_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FBoo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num1          int32                  `protobuf:"varint,1,opt,name=Num1,proto3" json:"Num1,omitempty"`
	Num2          int32                  `protobuf:"varint,2,opt,name=Num2,proto3" json:"Num2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FBoo) Reset() {
	*x = FBoo{}
	mi := &file_foo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FBoo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FBoo) ProtoMessage() {}

func (x *FBoo) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FBoo.ProtoReflect.Descriptor instead.
func (*FBoo) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{0}
}

func (x *FBoo) GetNum1() int32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *FBoo) GetNum2() int32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type FBooArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num1          int32                  `protobuf:"varint,1,opt,name=Num1,proto3" json:"Num1,omitempty"`
	Num2          int32                  `protobuf:"varint,2,opt,name=Num2,proto3" json:"Num2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FBooArgs) Reset() {
	*x = FBooArgs{}
	mi := &file_foo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FBooArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FBooArgs) ProtoMessage() {}

func (x *FBooArgs) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FBooArgs.ProtoReflect.Descriptor instead.
func (*FBooArgs) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{1}
}

func (x *FBooArgs) GetNum1() int32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *FBooArgs) GetNum2() int32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type FBooReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int32                  `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FBooReply) Reset() {
	*x = FBooReply{}
	mi := &file_foo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FBooReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FBooReply) ProtoMessage() {}

func (x *FBooReply) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FBooReply.ProtoReflect.Descriptor instead.
func (*FBooReply) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{2}
}

func (x *FBooReply) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_foo_proto protoreflect.FileDescriptor

var file_foo_proto_rawDesc = string([]byte{
	0x0a, 0x09, 0x66, 0x6f, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x65, 0x73,
	0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x2e, 0x0a, 0x04, 0x46, 0x42, 0x6f,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x75, 0x6d, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x4e, 0x75, 0x6d, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x75, 0x6d, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x75, 0x6d, 0x32, 0x22, 0x32, 0x0a, 0x08, 0x46, 0x42, 0x6f,
	0x6f, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x75, 0x6d, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x75, 0x6d, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x75, 0x6d,
	0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x75, 0x6d, 0x32, 0x22, 0x1d, 0x0a,
	0x09, 0x46, 0x42, 0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x4e, 0x75, 0x6d, 0x42, 0x11, 0x5a, 0x0f,
	0x2e, 0x2f, 0x3b, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_foo_proto_rawDescOnce sync.Once
	file_foo_proto_rawDescData []byte
)

func file_foo_proto_rawDescGZIP() []byte {
	file_foo_proto_rawDescOnce.Do(func() {
		file_foo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_foo_proto_rawDesc), len(file_foo_proto_rawDesc)))
	})
	return file_foo_proto_rawDescData
}

var file_foo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_foo_proto_goTypes = []any{
	(*FBoo)(nil),      // 0: test_service.FBoo
	(*FBooArgs)(nil),  // 1: test_service.FBooArgs
	(*FBooReply)(nil), // 2: test_service.FBooReply
}
var file_foo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foo_proto_init() }
func file_foo_proto_init() {
	if File_foo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foo_proto_rawDesc), len(file_foo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foo_proto_goTypes,
		DependencyIndexes: file_foo_proto_depIdxs,
		MessageInfos:      file_foo_proto_msgTypes,
	}.Build()
	File_foo_proto = out.File
	file_foo_proto_goTypes = nil
	file_foo_proto_depIdxs = nil
}
